% loadKernelYScaleYLabels.m
%
% Function to load y scales and y labels for kernel plotting, for when
% behavioral velocity units are all deg/s or for both mm/s and deg/s
%
% INPUTS:
%   whichEphys - string for which ephys variable (spikeRate or medFiltV) to
%       return y scales and labels for
%   degPerMM - 0 if using mm, actual conversion factor if using degrees
%
% UPDATED: 9/28/20 - HHY

function [yScale, yLabels] = loadKernelYScaleYLabels(whichEphys, degPerMM)

    if strcmpi(whichEphys, 'spikeRate')
        if (degPerMM)
            yScale = {[-3e-5 9e-5]...
                [-1e-5 2e-5]...
                [-6e-5 10e-5]...
                [-1e-5 4e-5]...
                [-0.5e-5 2.5e-5]...
                [-3 10]...
                [-20 20]...
                [-5 5]...
                [-2 10]...
                [-5 20]};

            yLabels = {'spikes/deg',...
                'spikes/deg', ...
                'spikes/deg', ...
                'spikes/deg', ...
                'spikes/deg', ...
                'deg/spike', ...
                'deg/spike', ...
                'deg/spike', ...
                'deg/spike', ...
                'deg/spike'};
        else
            yScale = {[-0.05 0.5]...
                [-2e-3 6e-3]...
                [-0.1 0.9]...
                [-5e-3 20e-3]...
                [-2e-3 12e-3]...
                [-2e-4 12e-4]...
                [-4e-3 4e-3]...
                [-1e-4 5e-4]...
                [-2e-3 10e-3]...
                [-0.005 0.045]};

            yLabels = {'spikes/mm',...
                'spikes/deg', ...
                'spikes/mm', ...
                'spikes/deg', ...
                'spikes/deg', ...
                'mm/spike', ...
                'deg/spike', ...
                'mm/spike', ...
                'deg/spike', ...
                'deg/spike'};
        end
    elseif (strcmpi(whichEphys, 'medFiltV'))

        if (degPerMM)
            yScale = {[-3e-5 9e-5]...
                [-1e-5 2e-5]...
                [-6e-5 10e-5]...
                [-1e-5 4e-5]...
                [-0.5e-5 2.5e-5]...
                [-3 10]...
                [-20 20]...
                [-5 5]...
                [-2 10]...
                [-5 20]};

            yLabels = {'mV/deg',...
                'mV/deg', ...
                'mV/deg', ...
                'mV/deg', ...
                'mV/deg', ...
                'deg/mV', ...
                'deg/mV', ...
                'deg/mV', ...
                'deg/mV', ...
                'deg/mV'};
        else
            yScale = {[-4e-4 16e-4]...
                [-1e-5 2e-5]...
                [-1e-3 2e-3]...
                [-1e-5 4e-5]...
                [-0.5e-5 2.5e-5]...
                [-0.15 0.4]...
                [-20 20]...
                [-0.3 0.3]...
                [-2 10]...
                [-5 20]};

            yLabels = {'mV/mm',...
                'mV/mm', ...
                'mV/mm', ...
                'mV/mm', ...
                'mV/mm', ...
                'mm/mV', ...
                'deg/mV', ...
                'mm/mV', ...
                'deg/mV', ...
                'deg/mV'};
        end
    end
end