% plotMeanAutoCorr.m
%
% Function to plot all autocorrelations. Also shows
%  number of flies in figure legend. Produces 1 plot, with subplots.
% Plot autocorrelation with (+) and (-), though symmetric.
% Requires the structs generated by extractKernels()
%
% INPUT:
%   autoCorr - autocorrelations struct from extractKernels()
%   autoCorrParams - autocorrelation parameters struct
%   allYLims - cell array of yLims for all subplots, if [], let matlab
%       scale
%   ttl - title for whole plot
%   withSEM - boolean for whether to include error shading
%   withIndiv - boolean for whether to include individual flies
%
% OUTPUT:
%   f - handle to figure
%   also produces plot
%
% CREATED: 9/4/19 - HHY
% UPDATED: 9/4/19 - HHY
%

function f = plotMeanAutoCorr(autoCorr, autoCorrParams, allYLims, ttl, ...
    withSEM, withIndiv)

    % get all fields in autoCorr struct (which autocorrelations computed)
    acFN = fieldnames(autoCorr);

    numSubplots = length(acFN);
    subplotRows = 2;
    subplotCols = ceil(numSubplots/subplotRows);
    
    % check if user provided yLims
    useYLims = ~isempty(allYLims);
    
    f = figure('units','normalized','outerposition',[0 0 1 0.8]);
    cmap = colormap('lines'); % get colormap
    
    % x-axis time, with (+) and (-) lags
    lags = [-1*fliplr(autoCorrParams.lags(2:end)) autoCorrParams.lags];
    
    for i = 1:numSubplots 
        
        % to put behavioral variables on 2nd line
        if i > 4
            whichSubplot = i + 1;
        else
            whichSubplot = i;
        end
        
        subplot(subplotRows, subplotCols, whichSubplot);
        hold on;
        
        % get allAutoCorr, mean, sem, (+) and (-) lags
        meanAutoCorr = [fliplr(autoCorr.(acFN{i}).meanAutoCorr(2:end)) ...
            autoCorr.(acFN{i}).meanAutoCorr];
        sem = [fliplr(autoCorr.(acFN{i}).sem(2:end)) ...
            autoCorr.(acFN{i}).sem];
        allAutoCorr = [fliplr(autoCorr.(acFN{i}).allAutoCorr(:,2:end)) ...
            autoCorr.(acFN{i}).allAutoCorr];
        
        % plot
        if withSEM
            plot_err_patch_v2(lags, meanAutoCorr, sem, ...
                cmap(i,:) * 0.8, cmap(i,:));
        else
            plot(lags, meanAutoCorr, 'Color', ...
                cmap(i,:), 'LineWidth', 1.5);
        end
        
        if withIndiv
            plot(lags, allAutoCorr, 'Color', cmap(i,:), 'LineWidth', 0.3);
        end
        
        xlabel('Time (s)');
        xlim([-1*autoCorrParams.maxLag autoCorrParams.maxLag]);

        if (useYLims)
            y = allYLims{i};
        else
            y = ylim;
        end
        
        % x-axis line
        line([-1*autoCorrParams.maxLag autoCorrParams.maxLag], [0,0],...
            'Color', 'black');
        
        % y-axis line
        line([0,0], y, 'Color', 'black');
        
        % y-axis limits
        ylim(y);
        
        ttlStr = sprintf('%s n = (%d)', acFN{i}, ...
            autoCorr.(acFN{i}).numFlies);
        
        title(ttlStr);       
        
    end
    
    suptitle(ttl);
    
end