% writePData.m
% 
% Function that takes in metadata structs and preprocessed data structs,
%  does some light re-organization, and saves the info into a pData
%  directory.
%
% INPUTS:
%   pDataDir - full path to pData directory
%   settings - settings struct output from ephysSettings() and saved in
%       metaDat.mat
%   exptInfo - experimental info struct from runEphysExpt() and saved in
%       metaDat.mat
%   preExptData - pre-experimental data struct, contains pipette, seal,
%       access, input resistance; Vm rest; holding current; generated by 
%       preExptRoutine; saved in preExptData.mat
%   inputParams - input parameters for trial, specific to experiment type;
%       saved in trial.mat file
%   ephysData - preprocessed ephys data struct; fields for voltage,
%       current, etc.; generated by preprocessEphysData()
%   ephysMeta - ephys metadata (gain, mode, filtering, start time);
%       generated by preprocessEphysData()
%   fictrac - preprocessed FicTrac data struct; fields for position, 
%       velocity in 3 axes; generated by preprocessFicTrac()
%   leg - preprocessed leg video data struct; fields for timing of leg
%       video; generated by preprocessLegVid()
%   opto - preprocessed optogenetic stimulation data struct; fields for
%       timing of stimulation; generated by preprocessOpto()
%   iInj - preprocessed current injection data struct; generated by
%       preprocessIInj()
%   visstim - preprocessed visual stimulus data struct; generated by
%       preprocessVisstimVInj()
%   trialName - string for name of trial (e.g. 'trial01' or 'cellAttached')
%
% OUTPUTS:
%   none, but writes pData file to pData directory
%
% CREATED: 9/6/20 - HHY
%
% UPDATED:
%   9/8/20 - HHY
%   9/24/21 - HHY - add _pData suffix to all pData file names
%   3/28/22 - HHY - add opto data struct
%   6/28/22 - HHY - add iInj data struct
%   1/16/23 - HHY - add visstim data struct
%
function writePData(pDataDir, settings, exptInfo, preExptData, ...
    inputParams, ephysData, ephysMeta, fictrac, leg, opto, iInj, ...
    visstim, trialName)

    % full path to pData file pDataDir/date_fly#_cell#_trialName.mat
   	pDataFileName = [pDataDir filesep exptInfo.dateDir '_' ...
        exptInfo.flyDir '_' exptInfo.cellDir '_' trialName ...
        '_pData.mat'];
    
    % correct exptCond for legFictracEphysIInj prior to 9/8/20
    if ((datetime(exptInfo.exptDate, 'InputFormat', 'yyMMdd') < ...
        datetime(2020,9,8)) && ...
        (strcmpi(inputParams.exptCond,'legFictracEphys')) && ...
        (isfield(inputParams, 'iInjProtocol')))
        exptCond = 'legFictracEphysIInj';
    else
        exptCond = inputParams.exptCond;
    end
    
    % correct startDelay, dataAvailExceeds, actualExptDuration fields of
    %  inputParams for legFictracEphys, legFictracEphysIInj experiments
    %  performed prior to 9/3/20
    if ((datetime(exptInfo.exptDate, 'InputFormat', 'yyMMdd') < ...
        datetime(2020,9,3)) && ...
        (contains(inputParams.exptCond,'legFictracEphys')))
        inputParams.startDelay = inputParams.startDelay / ...
            (settings.bob.sampRate)^2;
        inputParams.dataAvailExceeds = inputParams.dataAvailExceeds / ...
            (settings.bob.sampRate)^2;
        inputParams.actualExptDuration = inputParams.actualExptDuration / ...
            (settings.bob.sampRate)^2;
    end

    % remove unnecessary fields from inputParams before saving; exptCond
    %  moved 1 level up, channel info unneeded after preprocessing
    inputParams = rmfield(inputParams, {'exptCond', 'aInCh', 'aOutCh',...
        'dInCh', 'dOutCh'});
    
    % save the pData file
    % what's saved depends on experiment type
    switch exptCond
        case {'ephysRecording'}
            save(pDataFileName, 'exptCond', 'ephysData', 'ephysMeta',...
                'preExptData', 'settings', 'inputParams', '-v7.3');
        case {'ephysIInj'}
            save(pDataFileName, 'exptCond', 'ephysData', 'ephysMeta',...
                'iInj', 'preExptData', 'settings', 'inputParams', '-v7.3');
        case {'legFictracEphys', 'legvidFictracvidEphys'}
            save(pDataFileName, 'exptCond', 'ephysData', 'ephysMeta',...
                'preExptData', 'fictrac', 'leg', 'settings', ...
                'inputParams', '-v7.3');
        case {'legFictracEphysIInj'}
            save(pDataFileName, 'exptCond', 'ephysData', 'ephysMeta',...
                'preExptData', 'fictrac', 'leg', 'iInj', 'settings', ...
                'inputParams', '-v7.3');
        case {'legFictracOpto'}
            save(pDataFileName, 'exptCond','fictrac', 'leg', 'opto', ...
                'settings', 'inputParams', '-v7.3');
        case {'visstimLegFictracOptoVInj'}
            save(pDataFileName, 'exptCond','fictrac', 'leg', 'opto', ...
                'visstim', 'settings', 'inputParams', '-v7.3');
    end
    
    fprintf('\nSaved %s\n', trialName);
end
